## Topics in this Notebook:- <br/>


### Slicing

In [1]:
import numpy as np

In [2]:
#1D array
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
#2D array
b = np.array([[5.5,6.5,7.5],[8.8,9.5,7.5]])
b

array([[5.5, 6.5, 7.5],
       [8.8, 9.5, 7.5]])

In [4]:
# 3D array
x = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9],],
             [[11,12,13], [14,15,16], [17,18,19],],
            [[21,22,23], [24,25,26], [27,28,29]]])
print(x)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


##### Slicing rows

In [5]:
x[1]

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

#### Slicing columns

In [6]:
x[:,1,1]

array([ 5, 15, 25])

In [7]:
b[:,1]

array([6.5, 9.5])

### Dicing

In [8]:
x = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9],],
             [[11,12,13], [14,15,16], [17,18,19],],
            [[21,22,23], [24,25,26], [27,28,29]]])
print(x)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [9]:
print(x[1,2])

[17 18 19]


In [10]:
x[:,1,1]

array([ 5, 15, 25])

In [11]:
x[1,:,1]

array([12, 15, 18])

In [12]:
x[1:2,1:2]

array([[[14, 15, 16]]])

### Slicing & Dicing using pandas

In [13]:
import pandas as pd
df= pd.read_csv("loan.csv")
df.head()

Unnamed: 0  Unnamed: 0.1 loan_status  Principal  terms effective_date  \
0           0             0     PAIDOFF       1000     30     09-08-2016   
1           2             2     PAIDOFF       1000     30     09-08-2016   
2           3             3     PAIDOFF       1000     15     09-08-2016   
3           4             4     PAIDOFF       1000     30     09-09-2016   
4           6             6     PAIDOFF       1000     30     09-09-2016   

     due_date  age             education  Gender  
0  10-07-2016   45  High School or Below    male  
1  10-07-2016   33              Bechalor  female  
2   9/22/2016   27               college    male  
3  10-08-2016   28               college  female  
4  10-08-2016   29               college    male

In [14]:
df.loc[:,["education"]]

education
0   High School or Below
1               Bechalor
2                college
3                college
4                college
5                college
6                college
7                college
8                college
9   High School or Below
10               college
11               college
12  High School or Below
13               college
14  High School or Below
15  High School or Below
16  High School or Below
17               college
18               college

In [15]:
df.loc[:,["education","Principal"]]

education  Principal
0   High School or Below       1000
1               Bechalor       1000
2                college       1000
3                college       1000
4                college       1000
5                college       1000
6                college       1000
7                college        800
8                college        300
9   High School or Below       1000
10               college       1000
11               college        900
12  High School or Below       1000
13               college        800
14  High School or Below       1000
15  High School or Below       1000
16  High School or Below       1000
17               college        800
18               college       1000

In [16]:
df.iloc[:4]                  #iloc is integer based slicing

Unnamed: 0  Unnamed: 0.1 loan_status  Principal  terms effective_date  \
0           0             0     PAIDOFF       1000     30     09-08-2016   
1           2             2     PAIDOFF       1000     30     09-08-2016   
2           3             3     PAIDOFF       1000     15     09-08-2016   
3           4             4     PAIDOFF       1000     30     09-09-2016   

     due_date  age             education  Gender  
0  10-07-2016   45  High School or Below    male  
1  10-07-2016   33              Bechalor  female  
2   9/22/2016   27               college    male  
3  10-08-2016   28               college  female

In [17]:
x=df.iloc[:, 2:5]
x

loan_status  Principal  terms
0      PAIDOFF       1000     30
1      PAIDOFF       1000     30
2      PAIDOFF       1000     15
3      PAIDOFF       1000     30
4      PAIDOFF       1000     30
5      PAIDOFF       1000     30
6      PAIDOFF       1000     30
7      PAIDOFF        800     15
8      PAIDOFF        300      7
9      PAIDOFF       1000     15
10     PAIDOFF       1000     30
11     PAIDOFF        900      7
12     PAIDOFF       1000      7
13     PAIDOFF        800     15
14     PAIDOFF       1000     30
15     PAIDOFF       1000     15
16     PAIDOFF       1000     30
17     PAIDOFF        800     30
18     PAIDOFF       1000     30

## Concatenating and Transforming

### Adding new cases and variables

In [18]:
import pandas as pd

##### Adding new cases (rows)

In [19]:
df= pd.DataFrame({'A':[2,3,1],
                'B':[1,2,3],
                 'C':[4,5,6]})
df

A  B  C
0  2  1  4
1  3  2  5
2  1  3  6

In [20]:
df1= pd.DataFrame({'A' :[4],
                   'B':[4],
                   'C':[4]})
df1

A  B  C
0  4  4  4

In [21]:
df2 = df.append(df1)
df2

A  B  C
0  2  1  4
1  3  2  5
2  1  3  6
0  4  4  4

In [22]:
df2=df2.reset_index(drop=True)
df2

A  B  C
0  2  1  4
1  3  2  5
2  1  3  6
3  4  4  4

In [23]:
df2.loc[df2.last_valid_index()+1]=[5,5,5]     #match is necessary
df2

A  B  C
0  2  1  4
1  3  2  5
2  1  3  6
3  4  4  4
4  5  5  5

In [24]:
# must try if total number of columns does match in case of append().
dff = pd.DataFrame({'A':[1,2],
                   'B':[3,4]})

dff.append(df1)

A  B    C
0  1  3  NaN
1  2  4  NaN
0  4  4  4.0

##### Adding new variables(columns)

In [25]:
df = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3', 'K4', 'K5'],
                   'A': ['A0', 'A1', 'A2', 'A3', 'A4', 'A5']})
df

key   A
0  K0  A0
1  K1  A1
2  K2  A2
3  K3  A3
4  K4  A4
5  K5  A5

In [26]:
other = pd.DataFrame({'key': ['K0', 'K1', 'K2'],
                      'B': ['B0', 'B1', 'B2']})
other

key   B
0  K0  B0
1  K1  B1
2  K2  B2

Join DataFrames using their indexes.

In [27]:
df.join(other, lsuffix='_caller', rsuffix='_other')

key_caller   A key_other    B
0         K0  A0        K0   B0
1         K1  A1        K1   B1
2         K2  A2        K2   B2
3         K3  A3       NaN  NaN
4         K4  A4       NaN  NaN
5         K5  A5       NaN  NaN

If we want to join using the key columns, we need to set key to be the index in both df and other. The joined DataFrame will have key as its index.

In [28]:
df.set_index('key').join(other.set_index('key'))

A    B
key         
K0   A0   B0
K1   A1   B1
K2   A2   B2
K3   A3  NaN
K4   A4  NaN
K5   A5  NaN

Another option to join using the key columns is to use the on parameter. DataFrame.join always uses other’s index but we can use any column in df. This method preserves the original DataFrame’s index in the result.

In [29]:
df3=df.join(other.set_index('key'), on='key')
df3

key   A    B
0  K0  A0   B0
1  K1  A1   B1
2  K2  A2   B2
3  K3  A3  NaN
4  K4  A4  NaN
5  K5  A5  NaN

##### Removing rows..

In [30]:
df3 = df3.drop(df3.index[[2]])
df3

key   A    B
0  K0  A0   B0
1  K1  A1   B1
3  K3  A3  NaN
4  K4  A4  NaN
5  K5  A5  NaN

##### Removing columns

In [31]:
df4=df3.drop('A',1)          #you must specify an axis as part of the removal process (normally 1). 
df4

key    B
0  K0   B0
1  K1   B1
3  K3  NaN
4  K4  NaN
5  K5  NaN

## Sorting and shuffling

### Sorting

In [32]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'A': [2,1,2,3,3,5,4],
  'B': [1,2,3,5,4,2,5],
  'C': [5,3,4,1,1,2,3]})

print(df)

   A  B  C
0  2  1  5
1  1  2  3
2  2  3  4
3  3  5  1
4  3  4  1
5  5  2  2
6  4  5  3


In [33]:
df = df.sort_values(by=['A','B'], ascending=[True,False])
df = df.reset_index(drop=True)
print(df)

   A  B  C
0  1  2  3
1  2  3  4
2  2  1  5
3  3  5  1
4  3  4  1
5  4  5  3
6  5  2  2


### Shuffling

In [34]:
### Shufflingindex = df.index.tolist()
index = df.index.tolist()
print("index=",index)
np.random.shuffle(index)
df = df.loc[df.index[index]]
print(df)

index= [0, 1, 2, 3, 4, 5, 6]
   A  B  C
4  3  4  1
5  4  5  3
6  5  2  2
0  1  2  3
3  3  5  1
1  2  3  4
2  2  1  5


In [35]:
df = df.reset_index(drop=True)
print(df)

   A  B  C
0  3  4  1
1  4  5  3
2  5  2  2
3  1  2  3
4  3  5  1
5  2  3  4
6  2  1  5


### Aggregating Data at Any Level

A groupby operation involves some combination of splitting the object, applying a function, and combining the results. This can be used to group large amounts of data and compute operations on these groups.

In [36]:
df = pd.DataFrame({'Animal': ['Falcon', 'Falcon',
                              'Parrot', 'Parrot'],
                   'Max Speed': [380., 370., 24., 26.]})
df

Animal  Max Speed
0  Falcon      380.0
1  Falcon      370.0
2  Parrot       24.0
3  Parrot       26.0

In [37]:
df.groupby(['Animal']).mean()

Max Speed
Animal           
Falcon      375.0
Parrot       25.0

In [38]:
import pandas as pd
df = pd.DataFrame({'Person': ['Jack','Jack','Jack','Alex','Alex','John','John'],
'Gems': [1,2,3,5,4,2,5]})
df['S'] = df.groupby('Person')['Gems'].transform(np.sum)
df['M'] = df.groupby('Person')['Gems'].transform(np.mean)
df['V'] = df.groupby('Person')['Gems'].transform(np.var)
print(df)


  Person  Gems  S    M    V
0   Jack     1  6  2.0  1.0
1   Jack     2  6  2.0  1.0
2   Jack     3  6  2.0  1.0
3   Alex     5  9  4.5  0.5
4   Alex     4  9  4.5  0.5
5   John     2  7  3.5  4.5
6   John     5  7  3.5  4.5


Implement for practice:-
Consider dataset with student name, gender, Enrollmentno, 4 semester result with marks of each subject, his mobile number, city. Implement following in Python

1. Plot the graph showing result of student in each semester.
2. Plot the graph showing number of male and female students.