In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
b = np.array([[5.5,6.5,7.5],[8.0,9.5,7.5]])
b

array([[5.5, 6.5, 7.5],
       [8. , 9.5, 7.5]])

In [8]:
x = np.array([[[1,2,3],[4,5,6],[7,8,9],],
            [[11,12,13],[14,15,16],[17,18,19],],
            [[21,22,23],[24,25,26],[27,28,29]]])
x

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [12]:
#slicing rows
x[1]

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [13]:
#slicing columns
x[:,1]

array([[ 4,  5,  6],
       [14, 15, 16],
       [24, 25, 26]])

In [14]:
#dicing
print(x[1,1])

[14 15 16]


In [15]:
x[:,1,1]

array([ 5, 15, 25])

In [16]:
x[1,:,1]

array([12, 15, 18])

In [17]:
x[1:2,1:2]

array([[[14, 15, 16]]])

# Slicing and Dicing using Pandas

In [19]:
import pandas as pd
df = pd.read_csv("loan.csv")
df

Table A  Table B Table C
0        1   Loan 1      P1
1        2   Loan 2      P2
2        3   Loan 3      P3
3        4   Loan 4      P4
4        5   Loan 5      P5
5        6   Loan 6      P6
6        7   Loan 7      P7
7        8   Loan 8      P8
8        9   Loan 9      P9
9       10  Loan 10     P10

In [20]:
df.loc[:,["Table A"]]

Table A
0        1
1        2
2        3
3        4
4        5
5        6
6        7
7        8
8        9
9       10

In [21]:
df.loc[:,["Table A","Table B"]]

Table A  Table B
0        1   Loan 1
1        2   Loan 2
2        3   Loan 3
3        4   Loan 4
4        5   Loan 5
5        6   Loan 6
6        7   Loan 7
7        8   Loan 8
8        9   Loan 9
9       10  Loan 10

In [22]:
df.iloc[:4]

Table A Table B Table C
0        1  Loan 1      P1
1        2  Loan 2      P2
2        3  Loan 3      P3
3        4  Loan 4      P4

In [23]:
x=df.iloc[:,2:5]
x

Table C
0      P1
1      P2
2      P3
3      P4
4      P5
5      P6
6      P7
7      P8
8      P9
9     P10

# Concatenatng and Transforming

In [26]:
import pandas as pd


In [28]:
#Adding new cases and rows

df = pd.DataFrame({'A':[2,3,1],
                  'B':[1,2,3],
                  'C':[4,5,6]})
df

A  B  C
0  2  1  4
1  3  2  5
2  1  3  6

In [29]:
df1 = pd.DataFrame({'A':[4],
                   'B':[4],
                   'C':[4]})
df1

A  B  C
0  4  4  4

In [31]:
df2 = df.append(df1)
df2

A  B  C
0  2  1  4
1  3  2  5
2  1  3  6
0  4  4  4

In [32]:
df2 = df2.reset_index(drop = True)
df2

A  B  C
0  2  1  4
1  3  2  5
2  1  3  6
3  4  4  4

In [33]:
df.loc[df.last_valid_index()+1] = [5,5,5]
df

A  B  C
0  2  1  4
1  3  2  5
2  1  3  6
3  5  5  5

In [34]:
dff = pd.DataFrame({'A':[1,2],
                   'B':[3,4]})
dff.append(df1)

A  B    C
0  1  3  NaN
1  2  4  NaN
0  4  4  4.0

In [35]:
df = pd.DataFrame({'key':['k0','k1','k2','k3','k4','k5'],
                  'A':['a0','a1','a2','a3','a4','a5']})
df

key   A
0  k0  a0
1  k1  a1
2  k2  a2
3  k3  a3
4  k4  a4
5  k5  a5

In [36]:
other = pd.DataFrame({'key':['k0','k1','k2'],
                     'B':['b0','b1','b2']})
other

key   B
0  k0  b0
1  k1  b1
2  k2  b2

In [37]:
df.join(other,lsuffix='_caller',rsuffix='_other')

key_caller   A key_other    B
0         k0  a0        k0   b0
1         k1  a1        k1   b1
2         k2  a2        k2   b2
3         k3  a3       NaN  NaN
4         k4  a4       NaN  NaN
5         k5  a5       NaN  NaN

In [38]:
df.set_index('key').join(other.set_index('key'))

A    B
key         
k0   a0   b0
k1   a1   b1
k2   a2   b2
k3   a3  NaN
k4   a4  NaN
k5   a5  NaN

In [39]:
df3 = df.join(other.set_index('key'),on='key')
df3

key   A    B
0  k0  a0   b0
1  k1  a1   b1
2  k2  a2   b2
3  k3  a3  NaN
4  k4  a4  NaN
5  k5  a5  NaN

In [40]:
#removing rows and columns

df3 = df3.drop(df3.index[[2]])
df3

key   A    B
0  k0  a0   b0
1  k1  a1   b1
3  k3  a3  NaN
4  k4  a4  NaN
5  k5  a5  NaN

In [41]:
df4 = df3.drop('A',1)
df4

key    B
0  k0   b0
1  k1   b1
3  k3  NaN
4  k4  NaN
5  k5  NaN